version: '3'

services:

  app:
    build: .
    network_mode: host
    command: python run.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - elastic
      - mongo
    restart: on-failure

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    container_name: elasticsearch
    ports:
      - "9200:9200"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
